---
abstract: 'Tools for the CLI tools'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-SimpleHisto-XS-CLI
no_index:
  directory:
    - t
    - inc
requires:
  Math::SimpleHisto::XS: 1.28
  Pod::Usage: 0
  Term::Size: 0.200
  Test::More: 0.88
version: 1.07
